<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>socAIti</title>
    <link rel="stylesheet" href="styles.css">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        header {
            background: #333;
            color: #fff;
            padding: 10px 0;
            text-align: center;
        }
        nav {
            margin: 20px 0;
        }
        nav a {
            margin: 0 15px;
            color: #fff;
            text-decoration: none;
        }
        main {
            padding: 20px;
            background: #fff;
            max-width: 800px;
            margin: 20px auto;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        footer {
            text-align: center;
            padding: 10px 0;
            background: #333;
            color: #fff;
            position: relative;
            bottom: 0;
            width: 100%;
        }
    </style>
</head>
<body>

<header>
    <h1>Welcome to socAIti</h1>
    <nav>
        <a href="#about">About</a>
        <a href="#services">Services</a>
        <a href="#contact">Contact</a>
    </nav>
</header>

<main>
    <section id="about">
        <h2>About socAIti</h2>
        <p>socAIti is a platform that leverages artificial intelligence to enhance social interactions and community building. Our mission is to create a more connected world through innovative technology.</p>
    </section>

    <section id="services">
        <h2>Our Services</h2>
        <ul>
            <li>AI-Powered Community Insights</li>
            <li>Social Engagement Tools</li>
            <li>Data Analytics for Social Trends</li>
            <li>Custom AI Solutions for Organizations</li>
        </ul>
    </section>

    <section id="contact">
        <h2>Contact Us</h2>
        <p>If you have any questions or would like to learn more about our services, please reach out to us at <a href="mailto:info@socaiti.com">info@socaiti.com</a>.</p>
    </section>
</main>

<footer>
    <p>&copy; 2023 socAIti. All rights reserved.</p>
</footer>

</body>
</html>
